{!!Html::style('/resources/css/orijin/bootstrap.min.css',array(),true)!!}
{!!Html::style('/resources/css/orijin/jquery-ui.min.css',array(),true)!!}
{!!Html::style('/resources/css/orijin/aos.css',array(),true)!!}
{!!Html::style('/resources/css/orijin/animate.css',array(),true)!!}
{!!Html::style('/resources/css/orijin/ihover.css',array(),true)!!}
{!!Html::style('/resources/css/orijin/all.css',array(),true)!!}
{!!Html::style('/resources/css/orijin/site-style.css',array(),true)!!}
{!!Html::style('/resources/css/orijin/site-responsive.css',array(),true)!!}
{!!Html::style('/resources/css/orijin/dev.css',array(),true)!!}
